"Programme:Testdemos/AGA/Andromeda/Nexus7" AGAVANILLA SECS 30
"Programme:Testdemos/AGA/Delight/GraphistForSale" AGAVANILLA SECS 30
"Programme:Testdemos/AGA/Balance/Extreme/Extreme.exe" PLAINTURBO SECS 30
"Programme:Testdemos/AGA/BiosyntheticDesign/Tenebra" PLAINTURBO SECS 30
"Programme:Testdemos/AGA/Doom/SilenceIsBroken" PLAINTURBO SECS 30
"Programme:Testdemos/AGA/Complex/Real" AGAVANILLA SECS 30
"Programme:Testdemos/AGA/FocusDesign/BeKoolFool.exe" PLAINTURBO SECS 30
"Programme:Testdemos/AGA/Nature/Democratic" PLAINTURBO SECS 30
"Programme:Testdemos/AGA/Retire/CrOnOs" PLAINTURBO SECS 30
"Programme:Testdemos/AGA/Scoopex/TheSign/The_Sign.exe" PLAINTURBO SECS 30

